export const WEATHER_CONST_STRING = {
  GET_WEATHER_CURRENT_LOCATION: "GET_WEATHER_CURRENT_LOCATION",
  GET_WEATHER_CURRENT_LOCATION_REQUEST: "GET_WEATHER_CURRENT_LOCATION_REQUEST",
  GET_WEATHER_CURRENT_LOCATION_SUCCESS: "GET_WEATHER_CURRENT_LOCATION_SUCCESS",
  GET_WEATHER_CURRENT_LOCATION_FAILURE: "GET_WEATHER_CURRENT_LOCATION_FAILURE",
};
